export type AuthErrorCode =
  | "INVALID_CREDENTIALS"
  | "RATE_LIMITED"
  | "NETWORK_ERROR"
  | "TOKEN_EXPIRED"
  | "REFRESH_FAILED"
  | "REAUTH_REQUIRED"
  | "CORRUPTED_SESSION"
  | "STALE_AUTH_CONTEXT"
  | "AUTH_KILL_SWITCH"
  | "RECOVERY_TIMEOUT";
